### ISSUE TITLE
Tool likely does not work with the new 10.5 release

### ISSUE THREAD

**Issue by amazingandrogen** [tableau/TabMigrate#24]
Hey all- Just a quick reminder that this tool probably does will not work with 10.5+ releases, as 10.5 is using the new "Hyper" engine! 

Cheers!

**Comment by AirCooledNut** [comment]
I tried pushing a 10.3.1 site to a 10.5.0 Tableau Server and got the same error multiple times:
...
`The remote server returned an error: (400) Bad Request.`
...
d

**Comment by piyum24** [comment]
This might explain me not being able to log into Tabmigrate. 
@amazingandrogen, do you know if there will be an updated Tabmigrate tool, which supports Tableau v10.5?

**Comment by rferraton** [comment]
I tried my second solution (create a fork and branch for 10.5) you could try with the compiled new version of tabmigrate using 2.8 API urls https://github.com/aetperf/TabMigrate/tree/10.5-dev/TabRESTMigrate/bin/Release . for the moment i just tested extractions and it is working.

**Comment by piyum24** [comment]
@rferraton, appreciate the response and v10.5 patch fix!

I'm still unable to log into Tabmigrate. Do you know if having a SSO-enabled (SAML authentication) Tableau Server prevents you from using Tabmigrate?

**Comment by rferraton** [comment]
I use a classic login with this tool, no SAML sso login (which is in place).
Could you try with a classic user.?
Just create a new user (a Tableau server admin user) and define a password in the tableau server web interface.

**Comment by piyum24** [comment]
Oh got it, I can log in now! I'll report back if I'm able to export a site and import it elsewhere on the server. Thanks so much!

**Comment by amazingandrogen** [comment]
> This might explain me not being able to log into Tabmigrate.
> @amazingandrogen, do you know if there will be an updated Tabmigrate tool, which supports Tableau v10.5?

I have no idea- I don't use and am not familiar with it- I just work in support (github content is not created or maintained by our teams, so we don't interact with them)  and ran across a case where someone was frustrated that It did not work- a cursory glance suggested that it is likely that the software was created to work with non hyper content, and may not have been updated for the new data type!  I'm mainly just a passer by, trying to be helpful :) Good luck!

**Comment by amazingandrogen** [comment]
(also, i'm unfamiliar with github, so apparently I "closed" this, whatever that means, with no ability to undo the thing that I did. Sorry - hope that this does not impact anyone interacting on this thread!

**Comment by piyum24** [comment]
No worries, @amazingandrogen.

Following up with my earlier comment, refer to this link for the Tabmigrate version which support v10.5
https://github.com/aetperf/TabMigrate/tree/10.5-dev/TabRESTMigrate/bin/Release
