### ISSUE TITLE
Error logging into the Tabmigrate

### ISSUE THREAD

**Issue by venkat4467** [tableau/TabMigrate#39]
Hi,

 

I was trying to login to Tabmigrate using the same credentials to login into the Tableau server and Tableau desktop ( which is successful) but login into the Tabmigrate is throwing the following error.

 

![image](https://user-images.githubusercontent.com/49207340/55425041-872a8980-554f-11e9-8ea0-6eba0010caa3.png)

 

 

Any ideas?

 

Thanks much in advance.

**Comment by wrj2wmy** [comment]
"Could not create SSL/TLS secu" might caused by the HTTPS URL.
As far as I known, the TabMigrate has limited support for SSL/TLS.
Try the url using http protocol might help.

**Comment by IvoSalmreTableau** [comment]
TabMigrate has now been updated to use an updated version of the .NET Framework.  (It now can use TLS 1.2 security which Tableau Online now requires).

v1.14 has the updates.

**Comment by IvoSalmreTableau** [comment]
Fixed

**Comment by alitwaij** [comment]
Hi I am now also getting this error. I just installed and run the exe today and tried to login but it failed. We have SAML but i am using an account that is in tableau. I am also able to connect with those credentials in python via Rest API so not sure what the issue is. Any advice is welcome
