### ISSUE TITLE
Your security settings do not allow this application to be installed on your computer (fixed)

### ISSUE THREAD

**Issue by TimB1023** [tableau/TabMigrate#46]
This is just for anyone else that sees this error message.
I was unable to install the package using setup.exe. After some searching, I found this link here from Microsoft: [https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-configure-the-clickonce-trust-prompt-behavior?view=vs-2015&redirectedfrom=MSDN](url)
Once I made the changes tin my registry to "Enabling the ClickOnce Trust Prompt", the setup program worked. I still had a warning message, but now I had an option to install anyway.

**Comment by collinarnett** [comment]
@TimB1023 Please close the issue if the original problem is resolved.

**Comment by TimB1023** [comment]
@collinarnett
Sorry - I wasn't aware that it was still hanging around. Closing now!
Ttim
