### ISSUE TITLE
Show tab in workbook is not working

### ISSUE THREAD

**Issue by JananiHarikrishnan** [tableau/TabMigrate#6]
When i publish the workbook show tab option is not enabled. 
Please help me with how to enable it.

Thank you.

**Comment by IvoSalmreTableau** [comment]
@JananiHarikrishnan 

Thanks for the note. I've just added this functionality to TabMigrate.  It is available in TabMigrate_Setup v1.07.

Details:
   - Now, by default when content is downloaded from a server or site, each workbook (twb/twbx) gets a companion file next to it with a ".info.xml" file extension.
   - This ".info.xml" file contains whether or not the server had "Show Tabs" selected for this workbook.
   - When uploading content to a server or site, the uploader looks at each workbook to see if there is a companion ".info.xml" file. If there is, it pulls the Show Tabs preference from there. If no ".info/xml" file is there it defaults to not show tabs.
